apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    name: backend
spec:
  containers:
    - name: backend
      image: niklashakmann/backend:1083987b08f2cc6a0b40d9a2e3502e0261c53624
      ports:
        - containerPort: 9000
