apiVersion: v1
kind: Service
metadata:
  name: redis          # <- this becomes the DNS name backend connects to
spec:
  selector:
    name: redis         # <- matches the label on redis-pod.yml
  ports:
    - port: 6379
      targetPort: 6379
